substitutions:
  device_name: "gosundsp111"
  friendly_name: "Gosund SP111"
  # Higher value gives lower watt readout
  current_res: "0.00280"
  # Lower value gives lower voltage readout. In my case of about 15 of those devices this value is closest to my voltage meter
  voltage_div: "648"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp8285
  # This allows the device to restore the last saved relay state, either "ON" or "OFF" for the switch later in this config
  restore_from_flash: True

preferences:
  flash_write_interval: 5min # set to 5min to prevent wearing out the onboard flash module too quickly

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret fallback_hotspot_password

captive_portal:

wireguard:
  address: 10.5.0.3
  private_key: !secret gosund_wireguard_private_key
  peer_endpoint: !secret gosund_wireguard_peer_endpoint
  peer_port: !secret gosund_wireguard_peer_port
  peer_public_key: !secret gosund_wireguard_peer_public_key
  netmask: 255.255.255.0
  peer_allowed_ips:
    - 10.5.0.0/24

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Warsaw

# Enable Web server
web_server:
  port: 80
  version: 3
  log: False
  ota: False

text_sensor:
  - platform: version
    name: "Version"
    icon: mdi:cube-outline

binary_sensor:
  - platform: status
    name: "Status"
    device_class: connectivity

  # toggle relay on/off
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    id: "${device_name}_button_state"
    on_press:
      - switch.toggle: button_switch

  - platform: wireguard
    status:
      name: 'WireGuard Status'
      icon: mdi:vpn
      device_class: connectivity
      entity_category: "diagnostic"

sensor:
  - platform: total_daily_energy
    name: "Todays Usage"
    power_id: "power_wattage"
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:calendar-clock

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO04
    change_mode_every: 4
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    update_interval: 3s

    power:
      name: "Watt"
      unit_of_measurement: W
      id: "power_wattage"
      icon: mdi:gauge

status_led:
  pin:
    number: GPIO02
    inverted: True
  id: led_blue

output:
  - platform: gpio
    pin: GPIO00
    inverted: true
    id: led_red

switch:
  - platform: template
    name: "Switch"
    icon: mdi:power
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    lambda: 'return id(relay).state;'
    id: button_switch
    turn_on_action:
      - switch.turn_on: relay
      - output.turn_on: led_red
    turn_off_action:
      - switch.turn_off: relay
      - output.turn_off: led_red
  - platform: gpio
    pin: GPIO15
    id: relay

button:
  - platform: wake_on_lan
    name: "Wake server"
    target_mac_address: !secret server_mac_address
    icon: "mdi:lan-connect"
