esphome:
  name: ir-remote-control
  friendly_name: IR Remote Control

bk72xx:
  board: generic-bk7231n-qfn32-tuya
  
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
  actions:
    - action: send_sony_command
      variables:
        code: string
      then:
        - remote_transmitter.transmit_sony:
            data: !lambda 'return stoi(code, 0, 16);'
            nbits: 12
            repeat: 2

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

output:
  - platform: libretiny_pwm
    id: led
    pin: 24

light:
  - platform: monochromatic
    name: LED
    output: led

binary_sensor:
  - platform: gpio
    id: btn
    pin:
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true

remote_transmitter:
  pin: 7
  carrier_duty_percent: 50%

remote_receiver:
  pin:
    number: 8
    inverted: true
    mode:
      input: true
      pullup: true
  tolerance: 55%
  on_sony: 
    - lambda: |-
        ESP_LOGI("sony_ir", "Received Sony → data=0x%X, nbits=%u", x.data, x.nbits);