esphome:
  name: openthread-meteo-sensor
  friendly_name: OpenThread Meteo Sensor
  min_version: 2025.6.0
  name_add_mac_suffix: false

esp32:
  board: esp32-h2-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

web_server:
  version: 3

network:
  enable_ipv6: true

openthread:
  tlv: !secret openthread_tlv

i2c:
  sda: 10
  scl: 11
  scan: false

sensor:
  - platform: bmp280_i2c
    update_interval: never
    id: bmp280
    pressure:
      name: "Pressure"
      id: bmp280_pressure
      accuracy_decimals: 1
      on_value: 
        then:
          - component.update: sea_level_pressure
    

  - platform: aht10
    variant: AHT20
    update_interval: 5min
    temperature:
      name: "Temperature"
      id: aht20_temp
      accuracy_decimals: 1
      on_value: 
        then:
          - component.update: bmp280
    humidity:
      name: "Humidity"
      id: aht20_humidity
      accuracy_decimals: 1

  - platform: template
    name: "Sea level pressure"
    id: sea_level_pressure
    lambda: |-
      return id(bmp280_pressure).state / powf(1 - ((0.0065 * id(altitude).state) /
        (id(aht20_temp).state + (0.0065 * id(altitude).state) + 273.15)), 5.257); // in hPa
    update_interval: never
    unit_of_measurement: 'hPa'
    device_class: pressure
    state_class: measurement
    accuracy_decimals: 1

number:
  - platform: homeassistant
    name: "Altitude"
    id: altitude
    entity_id: input_number.altitude
